# 进程数
worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    server {
        listen       80;
        server_name  localhost; # 如果有域名这里写域名

        # 1. 前端静态资源 (Vue 打包后的文件)
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            # 解决 Vue Router History 模式刷新变 404 的问题
            try_files $uri $uri/ /index.html;
        }

        # 2. 后端接口转发 (反向代理)
        # 前端请求 /api/login -> Nginx -> 后端:8080/login
        location /api/ {
            proxy_pass http://hy-blog-backend:8080/; # 这里的 host 是 docker 服务名
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # 3. 图片资源映射
        # 访问 /upload/xxx.jpg -> Nginx 去容器里的 /app/uploads/ 找
        location /upload/ {
            alias /app/uploads/;
        }
    }
}